services:
  teach-sphere-test:
    build:
      context: .
      dockerfile: Dockerfile-test
    container_name: teach-sphere-test
    environment:
      SERVER_PORT: 8080
      TESTCONTAINERS_HOST_OVERRIDE: host.docker.internal
      SPRING_PROFILES_ACTIVE: test
      DOCKER_HOST: unix:///var/run/docker.sock
      TESTCONTAINERS_RYUK_DISABLED: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"