services:
  app:
    build:
      context: .
    container_name: teach_sphere_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    image: mysql:8.0
    container_name: teach_sphere_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
  redis:
    image: redis:7
    container_name: teach_sphere_redis
    restart: always
    ports:
      - "6379:6379"