services:
  app:
    build:
      context: .
    container_name: teach-sphere-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ] # Health check command
      interval: 30s # Check every 30 seconds
      timeout: 10s # Timeout after 10 seconds
      retries: 3 # Retry 3 times before marking as unhealthy
      start_period: 60s

