name: Test
on:
  pull_request:
    branches: [main]
jobs:
  test-docker:
    runs-on: ubuntu-latest
    env:
      SERVER_PORT: 8080
      TESTCONTAINERS_HOST_OVERRIDE: ""
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Run tests with docker-compose
        run: docker compose -f docker-compose-test.yml up --quiet-pull --abort-on-container-exit --exit-code-from teach-sphere-test
      - name: Clean up
        if: always()
        run: docker compose -f docker-compose-test.yml down -v